[supabase]
url = "https://eipyexlxmiqufmmtbdeu.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcHlleGx4bWlxdWZtbXRiZGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYxMzUxNjEsImV4cCI6MjAyMTcxMTE2MX0.tUdmPHfrIOlMZobgWNzZ9KjRMyw02uaE9nsVvjO1Q9I"
